# Embeddings
DEFAULT_CHUNK_SIZE = 1024
DEFAULT_CHUNK_OVERLAP = 200
EMBEDDING_MODEL_NAME = "text-embedding-ada-002"

MAX_FILE_SIZE_MB = 5
MAX_WORKERS = 5

MIN_USERNAME_LENGTH = 2
MAX_USERNAME_LENGTH = 20

GEMINI_25_MAX_INPUT_TOKENS = 1_048_576
